#!/usr/bin/perl
# Perl module to run 
############################################################
print "Note: Each run calculates 10 points, e.g. 0 means 0~9, 1 means 10~19, 10 means 100~109 etc.\n";
print "Give the start run number [0~3000]\n";
$srunnum = <STDIN>;
chop($srunnum);

print "Give the end run number [0~3000]\n";
$erunnum = <STDIN>;
chop($erunnum);

if($srunnum<=$erunnum){
	for($i=$srunnum;$i<=$erunnum;$i++){
		print `./gofarm_f1K $i  \n`;
		#print `./gofarm_all $i  \n`;
		#print `./gofarm_swif $i  \n`;
	}
}
else {
    die "End run number should be greater than start run number\n";
}
