#!/bin/sh
RNUM=$1
COUNT=0
while [ $COUNT -lt 10 ]; do
	let RNUM0=RNUM*10+COUNT
	if ! [ -e "./results/transversity_u_"$RNUM0".dat" ]; then
		echo "Working on N = "$RNUM0
		collins.exe -DATA $RNUM0 
	else
		echo "Job is done for N = "$RNUM0", skipped!"
	fi
	let COUNT=COUNT+1
done
