#!/bin/sh

# Usage: farm_list
#
# This script creates batch_krun and jscript_krun in batch_files directory
# and submits the job to the farms
#
# Feb. 22, 2011 Zhihong Ye
#

home=/work/halla/solid/yez/TMDs/collins/
# home=$(PWD)     
# The directory where replay_script is
# Event you want to start with,gtotal=-1 means to replay all
username=${USER}@jlab.org    # email which will be notify when the job is done
#
# Check whether the raw data are in cache or not
#

#
# Function to check if input is an integer
#
is_integer() {
 case $1 in
  *[!0-9]*) return 1;;
  *) return 0;;
 esac
}

rnum=$1

if ! [ -d batch_files ]
	then 
	echo "----------------------------------------------------------------"
	echo "I need batch_files directory. I am going to create it"
	echo  
	mkdir batch_files
    fi
    
#
    echo
#
# Write file batch_krun
#
    rm -f batch_files/batch_${rnum}
    echo "#!/bin/sh" > batch_files/batch_${rnum}
    echo "cd "${home}"/" >>batch_files/batch_${rnum}
	COUNT=0
	while [ $COUNT -lt 10 ]; do
		let rnum_sub=rnum*10+COUNT
		echo "collins.exe -DATA "$rnum_sub" ">>batch_files/batch_${rnum}
	    let COUNT=COUNT+1
	done
	#  
    chmod +x batch_files/batch_${rnum}
    
    echo "batch_files/batch_"${rnum}" has been created!"
    echo " "
    
#
# Write the jsub script
#
    rm -f batch_files/jscript_${rnum}
    echo "PROJECT     solid" > batch_files/jscript_${rnum}
    echo "COMMAND     "$home"/batch/batch_files/batch_"${rnum} >>batch_files/jscript_${rnum}
    echo "JOBNAME     collins_"${rnum} >>batch_files/jscript_${rnum}
    echo "TRACK       simulation" >> batch_files/jscript_${rnum}
    echo "TIME        2000" >>batch_files/jscript_${rnum}
    echo "MEMORY      2000 MB" >>batch_files/jscript_${rnum}
    echo "OS          centos65" >>batch_files/jscript_${rnum}
    
    echo "batch_files/jscript_"${rnum}" has been created."
    echo " " 
    echo "Now, let us wait for the farms..."
    echo " "
#
# Submit job to the farm
    jsub batch_files/jscript_${rnum}
#
#
    echo "Job "${rnum} "has been submited!"
    echo
    echo
#
    sleep 0.1
    
